services:
  emulate:
    build:
      dockerfile: ./Dockerfile
    restart: always
    networks:
      devcontainer-proxy:
        aliases:
          - emulate.localhost
    labels:
      - traefik.enable=true
      - traefik.http.routers.emulate.rule=Host(`emulate.localhost`)
      - traefik.http.routers.emulate.service=emulate
      - traefik.http.services.emulate.loadbalancer.server.port=80
  socket-proxy:
    image: linuxserver/socket-proxy:3.4.4
    container_name: socket-proxy
    environment:
      CONTAINERS: 1
      EVENTS: 1
      PING: 1
      VERSION: 1
      POST: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - docker-socket
    read_only: true
    tmpfs:
      - /run
    restart: always
  traefik:
    image: traefik:v3
    depends_on:
      - socket-proxy
    restart: always
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.endpoint=tcp://socket-proxy:2375
      - --providers.docker.watch=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=devcontainer-proxy
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
    networks:
      - devcontainer-proxy
      - docker-socket
    labels:
      - traefik.enable=true
      - traefik.docker.network=devcontainer-proxy
      - traefik.http.routers.traefik.rule=Host(`traefik.localhost`)
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.service=api@internal

networks:
  devcontainer-proxy:
    external: true
  docker-socket:
    internal: true