google:
  users:
    - email: user1@example.com
      name: Test User 1
    - email: user2@example.com
      name: Test User 2
    - email: user3@example.com
      name: Test User 3
    - email: user4@example.com
      name: Test User 4
    - email: user5@example.com
      name: Test User 5
    - email: user6@example.com
      name: Test User 6
    - email: user7@example.com
      name: Test User 7
    - email: user8@example.com
      name: Test User 8
    - email: user9@example.com
      name: Test User 9
  oauth_clients:
    - client_id: my-client-id.apps.googleusercontent.com
      client_secret: GOCSPX-secret
      redirect_uris:
        - http://127.0.0.1:3000/auth/oauth2/callback/google-emulate
        - http://127.0.0.1:3001/auth/oauth2/callback/google-emulate
        - http://127.0.0.1:3002/auth/oauth2/callback/google-emulate
        - http://127.0.0.1:3003/auth/oauth2/callback/google-emulate
        - http://127.0.0.1:3004/auth/oauth2/callback/google-emulate
        - http://127.0.0.1:3005/auth/oauth2/callback/google-emulate
        - http://127.0.0.1:3006/auth/oauth2/callback/google-emulate
        - http://127.0.0.1:3007/auth/oauth2/callback/google-emulate
        - http://127.0.0.1:3008/auth/oauth2/callback/google-emulate
        - http://127.0.0.1:3009/auth/oauth2/callback/google-emulate
        - http://127.0.0.1:3010/auth/oauth2/callback/google-emulate
        - http://127.0.0.1:3012/auth/oauth2/callback/google-emulate
        - http://127.0.0.1:3013/auth/oauth2/callback/google-emulate
        - http://127.0.0.1:3014/auth/oauth2/callback/google-emulate
        - http://127.0.0.1:3015/auth/oauth2/callback/google-emulate
        - http://127.0.0.1:3016/auth/oauth2/callback/google-emulate
        - http://127.0.0.1:3017/auth/oauth2/callback/google-emulate
        - http://127.0.0.1:3018/auth/oauth2/callback/google-emulate
        - http://127.0.0.1:3019/auth/oauth2/callback/google-emulate
        - http://localhost:5260/auth/oauth2/callback/google-emulate
        - http://localhost:5261/auth/oauth2/callback/google-emulate
        - http://localhost:5262/auth/oauth2/callback/google-emulate
        - http://localhost:5263/auth/oauth2/callback/google-emulate
        - http://localhost:5264/auth/oauth2/callback/google-emulate
        - http://localhost:5265/auth/oauth2/callback/google-emulate
        - http://localhost:5266/auth/oauth2/callback/google-emulate
        - http://localhost:5267/auth/oauth2/callback/google-emulate
        - http://localhost:5268/auth/oauth2/callback/google-emulate
        - http://localhost:5269/auth/oauth2/callback/google-emulate

